moves bucket to sdk v2
guardian/prism pull request #97
Opened 2020-11-24 14:15 UTC by Nirvikalpa108

### What does this change?
This continues the work started in PR #95 to move prism to AWS SDK v2

2020-11-27 09:44 UTC, sihil requested changes
A minor improvement otherwise looks good.

2020-11-27 09:44 UTC, sihil commented on app/collectors/bucket.scala
> +      if (bucketRegion == originRegion.toString) {
I'd prefer using `id` here. As it happens `toString` is the same and will work, but `id` would be cleaner and more explicit.
```suggestion
      if (bucketRegion == originRegion.id) {
```

2020-11-27 13:02 UTC, sihil approved these changes

2020-11-30 06:28 UTC, Nirvikalpa108 commented
After switching to java instance time from joda datetime and running `$ diff -I href <(jq -S '.data.buckets | sort_by(.arn)' pBuckets.json) <(jq -S '.data.buckets | sort_by(.arn)' cBuckets.json)`, the only difference is that CODE does not include milliseconds. We don't think any application that ingests prism data is likely to be checking miliseconds, so this should be good to deploy. 

```
<     "createdTime": "2020-06-25T07:06:41.000Z",
---
>     "createdTime": "2020-06-25T07:06:41Z",
```

2020-11-30 06:34 UTC, merged